### ISSUE TITLE
Operand/shape error

### ISSUE THREAD

**Issue by francisjervis** [nghuyong/rasa-faq-bot#11]
Sending a query from Rasa to the action server generates the following error:
`score = np.sum((self.standard_questions_encoder * query_vector), axis=1) / (self.standard_questions_encoder_len * (np.sum(query_vector * query_vector) ** 0.5))
ValueError: operands could not be broadcast together with shapes (1000,3072) (768,)`
The very similar code from the bert-as-service example,
`score = np.sum(query_vec * doc_vecs, axis=1) / np.linalg.norm(doc_vecs, axis=1)`
works as expected.

**Comment by itrare** [comment]
@francisjervis Hey actually I also got the same shape error but soon find that I was using the wrong variable. It works like charm. Thanks to @nghuyong and contributors...😉
